name: siglip2-so400m-deployment
docker:
  image: "algonum1/siglip2-runpod:latest"
  dockerfile: "./Dockerfile"
resources:
  gpu:
    type: "NVIDIA_RTX_A6000"
    count: 1
  cpu:
    cores: 4
  memory:
    size: "16GB"
  storage:
    size: "50GB"
environment:
  TRANSFORMERS_CACHE: "/runpod-volume/.cache/huggingface"
  HF_HOME: "/runpod-volume/.cache/huggingface"
  CUDA_VISIBLE_DEVICES: "0"
serverless:
  handler: "runpod_handler.py"
  max_workers: 2
  idle_timeout: 600
  execution_timeout: 300
  startup_timeout: 600
endpoints:
  - name: "classify"
    input_schema:
      type: "object"
      properties:
        task:
          type: "string"
          default: "classify"
        image_url:
          type: "string"
        image_base64:
          type: "string"
        labels:
          type: "string"
          default: "cat,dog,car,plane,person"
      required: ["task"]
  - name: "embed"
    input_schema:
      type: "object"
      properties:
        task:
          type: "string"
          default: "embed"
        image_url:
          type: "string"
        image_base64:
          type: "string"
      required: ["task"]
health_check:
  endpoint: "/health"
  interval: 30
  timeout: 10
  retries: 3